/*
 * ibkr
 *
 * ibkr API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Quotes struct for Quotes
type Quotes struct {
	Date []int32 `json:"date,omitempty"`
	Open []float64 `json:"open,omitempty"`
	High []float64 `json:"high,omitempty"`
	Low []float64 `json:"low,omitempty"`
	Close []float64 `json:"close,omitempty"`
	Volume []int32 `json:"volume,omitempty"`
	Average []float64 `json:"average,omitempty"`
	Adx []float64 `json:"adx,omitempty"`
	Rsi []float64 `json:"rsi,omitempty"`
	MacdValue []float64 `json:"macd_value,omitempty"`
	MacdSignal []float64 `json:"macd_signal,omitempty"`
	MacdHist []float64 `json:"macd_hist,omitempty"`
	BbandsHigh []float64 `json:"bbands_high,omitempty"`
	BbandsMiddle []float64 `json:"bbands_middle,omitempty"`
	BbandsLow []float64 `json:"bbands_low,omitempty"`
}
