/*
 * ibkr
 *
 * ibkr API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Portfolio struct for Portfolio
type Portfolio struct {
	Data []PortfolioData `json:"data,omitempty"`
}
