/*
 * ibkr
 *
 * ibkr API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Scan struct for Scan
type Scan struct {
	Data []ScanData `json:"data,omitempty"`
}
