/*
 * ibkr
 *
 * ibkr API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PortfolioData struct for PortfolioData
type PortfolioData struct {
	Position int32 `json:"position,omitempty"`
	MarketPrice float32 `json:"marketPrice,omitempty"`
	MarketValue float32 `json:"marketValue,omitempty"`
	AverageCost float32 `json:"averageCost,omitempty"`
	UnrealizedPNL float32 `json:"unrealizedPNL,omitempty"`
	RealizedPNL float32 `json:"realizedPNL,omitempty"`
	Account string `json:"account,omitempty"`
	ConId int64 `json:"conId,omitempty"`
	Ticker string `json:"ticker,omitempty"`
	LocalSymbol string `json:"localSymbol,omitempty"`
	Currency string `json:"currency,omitempty"`
	PrimaryExchange string `json:"primaryExchange,omitempty"`
	Routing string `json:"routing,omitempty"`
}
